# Generated by Django 5.2.9 on 2025-12-05 14:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalysisJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("extracting", "Extracting Questions"),
                            ("classifying", "Classifying"),
                            ("embedding", "Generating Embeddings"),
                            ("detecting", "Detecting Duplicates"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("progress", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("questions_extracted", models.PositiveIntegerField(default=0)),
                ("questions_classified", models.PositiveIntegerField(default=0)),
                ("duplicates_found", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Analysis Job",
                "verbose_name_plural": "Analysis Jobs",
                "ordering": ["-created_at"],
            },
        ),
    ]
