# Generated by Django 5.2.9 on 2025-12-05 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analysis", "0001_initial"),
        ("papers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisjob",
            name="paper",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analysis_jobs",
                to="papers.paper",
            ),
        ),
    ]
