# Generated by Django 5.2.9 on 2025-12-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisjob',
            name='status_detail',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
