# Generated by Django 5.2.9 on 2025-12-05 14:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("question_number", models.CharField(blank=True, max_length=20)),
                ("text", models.TextField()),
                ("sub_questions", models.JSONField(blank=True, default=list)),
                ("marks", models.PositiveIntegerField(blank=True, null=True)),
                ("topics", models.JSONField(blank=True, default=list)),
                ("keywords", models.JSONField(blank=True, default=list)),
                (
                    "difficulty",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "bloom_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("remember", "Remember"),
                            ("understand", "Understand"),
                            ("apply", "Apply"),
                            ("analyze", "Analyze"),
                            ("evaluate", "Evaluate"),
                            ("create", "Create"),
                        ],
                        max_length=15,
                    ),
                ),
                ("embedding", models.JSONField(blank=True, null=True)),
                ("is_duplicate", models.BooleanField(default=False)),
                ("similarity_score", models.FloatField(blank=True, null=True)),
                ("module_manually_set", models.BooleanField(default=False)),
                ("difficulty_manually_set", models.BooleanField(default=False)),
                (
                    "duplicate_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duplicates",
                        to="questions.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
                "ordering": ["question_number"],
            },
        ),
    ]
