"""
Classification rule models.
"""
from django.db import models
from apps.core.models import BaseModel


class ClassificationRule(BaseModel):
    """User-defined rule for question classification."""
    
    class RuleType(models.TextChoices):
        MODULE = 'module', 'Module Classification'
        TOPIC = 'topic', 'Topic Detection'
        DIFFICULTY = 'difficulty', 'Difficulty Assessment'
        BLOOM = 'bloom', 'Bloom\'s Taxonomy'
    
    subject = models.ForeignKey(
        'subjects.Subject',
        on_delete=models.CASCADE,
        related_name='rules'
    )
    
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    rule_type = models.CharField(
        max_length=20,
        choices=RuleType.choices
    )
    
    # Natural language rule definition
    natural_language = models.TextField(
        help_text='Define the rule in plain English'
    )
    
    # Compiled Python code (generated by LLM)
    compiled_code = models.TextField(blank=True)
    
    # Rule priority (higher = more important)
    priority = models.PositiveIntegerField(default=0)
    
    # Status
    is_active = models.BooleanField(default=True)
    is_validated = models.BooleanField(default=False)
    validation_error = models.TextField(blank=True)
    
    class Meta:
        verbose_name = 'Classification Rule'
        verbose_name_plural = 'Classification Rules'
        ordering = ['-priority', 'name']
    
    def __str__(self):
        return f"{self.name} ({self.get_rule_type_display()})"
