# Generated by Django 5.2.9 on 2025-12-05 14:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("number", models.PositiveIntegerField(default=1)),
                ("description", models.TextField(blank=True)),
                ("topics", models.JSONField(blank=True, default=list)),
                ("keywords", models.JSONField(blank=True, default=list)),
                (
                    "weightage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Expected weightage percentage in exams",
                        max_digits=5,
                    ),
                ),
            ],
            options={
                "verbose_name": "Module",
                "verbose_name_plural": "Modules",
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(blank=True, max_length=50)),
                ("description", models.TextField(blank=True)),
                (
                    "syllabus_file",
                    models.FileField(blank=True, null=True, upload_to="syllabi/"),
                ),
                ("university", models.CharField(blank=True, max_length=255)),
                ("exam_board", models.CharField(blank=True, max_length=255)),
                ("year", models.CharField(blank=True, max_length=50)),
                ("settings", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Subject",
                "verbose_name_plural": "Subjects",
                "ordering": ["-created_at"],
            },
        ),
    ]
