# Generated by Django 5.2.9 on 2025-12-05 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("subjects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modules",
                to="subjects.subject",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subject",
            unique_together={("user", "name", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="module",
            unique_together={("subject", "number")},
        ),
    ]
