# Generated by Django 5.2.9 on 2025-12-08 17:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamPattern",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(default="Default Pattern", max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "pattern_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Question number to module mapping",
                    ),
                ),
                ("part_a_marks", models.PositiveIntegerField(default=3)),
                ("part_b_marks", models.PositiveIntegerField(default=14)),
                (
                    "subject",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_pattern",
                        to="subjects.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam Pattern",
                "verbose_name_plural": "Exam Patterns",
            },
        ),
    ]
