# Generated by Django 5.2.9 on 2025-12-05 14:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Paper",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=255)),
                ("year", models.CharField(blank=True, max_length=50)),
                ("exam_type", models.CharField(blank=True, max_length=100)),
                ("file", models.FileField(upload_to="papers/")),
                ("file_hash", models.CharField(blank=True, max_length=64)),
                ("page_count", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("processing_error", models.TextField(blank=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("raw_text", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Paper",
                "verbose_name_plural": "Papers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaperPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_number", models.PositiveIntegerField()),
                ("text_content", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="paper_pages/"),
                ),
            ],
            options={
                "ordering": ["page_number"],
            },
        ),
    ]
