# Generated by Django 5.2.9 on 2025-12-05 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("papers", "0001_initial"),
        ("subjects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="papers",
                to="subjects.subject",
            ),
        ),
        migrations.AddField(
            model_name="paperpage",
            name="paper",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pages",
                to="papers.paper",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="paperpage",
            unique_together={("paper", "page_number")},
        ),
    ]
