# Generated by Django 5.2.9 on 2025-12-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='progress_percent',
            field=models.PositiveIntegerField(default=0, help_text='Overall progress percentage'),
        ),
        migrations.AddField(
            model_name='paper',
            name='questions_classified',
            field=models.PositiveIntegerField(default=0, help_text='Number of questions classified'),
        ),
        migrations.AddField(
            model_name='paper',
            name='questions_extracted',
            field=models.PositiveIntegerField(default=0, help_text='Number of questions extracted'),
        ),
        migrations.AddField(
            model_name='paper',
            name='status_detail',
            field=models.CharField(blank=True, help_text='Current operation detail', max_length=255),
        ),
    ]
