# Generated by Django 5.2.9 on 2025-12-08 17:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("subjects", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopicCluster",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("topic_name", models.CharField(max_length=500)),
                ("normalized_key", models.CharField(db_index=True, max_length=500)),
                ("representative_text", models.TextField(blank=True)),
                (
                    "frequency_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of exams where this topic appears"
                    ),
                ),
                (
                    "years_appeared",
                    models.JSONField(
                        blank=True, default=list, help_text="List of years/exam names"
                    ),
                ),
                (
                    "total_marks",
                    models.PositiveIntegerField(
                        default=0, help_text="Total marks across all occurrences"
                    ),
                ),
                (
                    "priority_tier",
                    models.CharField(
                        choices=[
                            ("tier_1", "Top Priority (4+ exams)"),
                            ("tier_2", "High Priority (3 exams)"),
                            ("tier_3", "Medium Priority (2 exams)"),
                            ("tier_4", "Low Priority (1 exam)"),
                        ],
                        default="tier_4",
                        max_length=10,
                    ),
                ),
                ("part_a_count", models.PositiveIntegerField(default=0)),
                ("part_b_count", models.PositiveIntegerField(default=0)),
                (
                    "module",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topic_clusters",
                        to="subjects.module",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topic_clusters",
                        to="subjects.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Topic Cluster",
                "verbose_name_plural": "Topic Clusters",
                "ordering": ["-frequency_count", "topic_name"],
                "indexes": [
                    models.Index(
                        fields=["subject", "module"],
                        name="analytics_t_subject_64c306_idx",
                    ),
                    models.Index(
                        fields=["priority_tier"], name="analytics_t_priorit_415c66_idx"
                    ),
                    models.Index(
                        fields=["-frequency_count"],
                        name="analytics_t_frequen_c86e59_idx",
                    ),
                ],
            },
        ),
    ]
