# Generated by Django 5.2.9 on 2025-12-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topiccluster',
            name='question_count',
            field=models.PositiveIntegerField(default=0, help_text='Total number of questions in this cluster'),
        ),
    ]
