# Generated by Django 5.2.9 on 2025-12-05 14:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClassificationRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("module", "Module Classification"),
                            ("topic", "Topic Detection"),
                            ("difficulty", "Difficulty Assessment"),
                            ("bloom", "Bloom's Taxonomy"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "natural_language",
                    models.TextField(help_text="Define the rule in plain English"),
                ),
                ("compiled_code", models.TextField(blank=True)),
                ("priority", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("is_validated", models.BooleanField(default=False)),
                ("validation_error", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Classification Rule",
                "verbose_name_plural": "Classification Rules",
                "ordering": ["-priority", "name"],
            },
        ),
    ]
